[#ftl]
[#-- @implicitly included --]
[#-- @ftlroot --]
[#-- @ftlvariable name="now" type="java.util.Date" --]
[#-- @ftlvariable name="projectName" type="String" --]
[#-- @ftlvariable name="projectClassName" type="String" --]
[#-- @ftlvariable name="projectRemark" type="String" --]
[#-- @ftlvariable name="jdbc" type="com.code.smither.project.base.model.DatabaseJdbc"  --]
[#-- @ftlvariable name="table" type="com.code.smither.project.base.model.Table" --]
[#-- @ftlvariable name="organTable" type="com.code.smither.project.base.model.Table" --]
[#-- @ftlvariable name="loginTable" type="com.code.smither.project.base.model.Table" --]
[#-- @ftlvariable name="orgColumn" type="com.code.smither.project.base.model.TableColumn" --]
[#-- @ftlvariable name="codeColumn" type="com.code.smither.project.base.model.TableColumn" --]
[#-- @ftlvariable name="author" type="java.lang.String" --]
[#-- @ftlvariable name="className" type="java.lang.String" --]
[#-- @ftlvariable name="packageName" type="String" --]
[#-- @ftlvariable name="appName" type="String" --]
[#-- @ftlvariable name="appTitle" type="String" --]
[#-- @ftlvariable name="appDetail" type="String" --]
[#-- @ftlvariable name="dbType" type="String" --]
[#-- @ftlvariable name="lang" type="String" --]
[#-- @ftlvariable name="tables" type="java.util.List<com.code.smither.project.base.model.Table>" --]
[#-- @ftlvariable name="tablesForRoute" type="java.util.List<com.code.smither.project.base.model.Table>" --]
[#-- @ftlvariable name="loginTables" type="java.util.List<com.code.smither.project.base.model.Table>" --]
[#-- @ftlvariable name="features" type="com.code.smither.project.base.model.Features" --]
[#-- @ftlvariable name="tools" type="com.code.smither.project.base.util.BaseTools" --]
[#-- @ftlvariable name="hasLogin" type="boolean" --]
[#-- @ftlvariable name="hasOrgan" type="boolean" --]
[#-- @ftlvariable name="hasCode" type="boolean" --]
[#-- @ftlvariable name="hasLongId" type="boolean" --]
[#-- @ftlvariable name="hasStringId" type="boolean" --]
[#-- @ftlvariable name="isHasAutoIncrementId" type="boolean" --]
[#-- @ftlvariable name="hasMultiLogin" type="boolean" --]



