[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="now" type="java.util.Date" --]
[#-- @ftlvariable name="projectName" type="String" --]
[#-- @ftlvariable name="table" type="com.code.smither.project.base.model.Table" --]
[#-- @ftlvariable name="organTable" type="com.code.smither.project.base.model.Table" --]
[#-- @ftlvariable name="loginTable" type="com.code.smither.project.base.model.Table" --]
[#-- @ftlvariable name="orgColumn" type="com.code.smither.project.base.model.TableColumn" --]
[#-- @ftlvariable name="codeColumn" type="com.code.smither.project.base.model.TableColumn" --]
[#-- @ftlvariable name="author" type="java.lang.String" --]
[#-- @ftlvariable name="className" type="java.lang.String" --]
[#-- @ftlvariable name="packageName" type="String" --]
[#-- @ftlvariable name="dbType" type="String" --]
[#-- @ftlvariable name="lang" type="String" --]
[#-- @ftlvariable name="tables" type="java.util.List<com.code.smither.project.base.model.Table>" --]
[#-- @ftlvariable name="hasLogin" type="boolean" --]
[#-- @ftlvariable name="hasOrgan" type="boolean" --]
[#-- @ftlvariable name="hasCode" type="boolean" --]


